### ISSUE TITLE
Can't purchase items on Skyloft

### ISSUE THREAD

**Issue by OTFree** [lepelog/sslib#44]
Running version 1.02, randomized shops, but whenever I try to purchase anything, nothing happens (as if I chose "no"). This applies to the shield, quiver, slingshot seed back etc.

Anyone sure why this happens? Playing on console

**Comment by azer67** [comment]
This is because you do not have an adventure pouch yet. But it is true that the shops are broken. The sacred shield is also currently unobtainable

**Comment by lepelog** [comment]
all shields can now be bought from the start (if you have enough rupees)
