### ISSUE TITLE
Game version unclear

### ISSUE THREAD

**Issue by blackoutroulette** [lepelog/sslib#45]
What does "Take a clean E 1.00 ISO" mean? How to find out which version I have? The version on the back of my game says RVL L SOUP and RVL-SOUP-NOE.

**Comment by azer67** [comment]
You need to verify the hashes on dolphin. Right click on your iso in dolphin, go to properties, info, compute MD5 checksum, and check if that corresoonds to the checksum in the readme.
But that won't be necessary for your iso. SOUP is the PAL version, but you need the NTSC-U version (which is SOUE). So it's automatically the wrong one

**Comment by blackoutroulette** [comment]
Thanks, it would be nice if you could update the readme with this info like: "Take a clean NTSC-U 1.0 (SOUE) ISO file and make sure  to verify the hashes..."
