### ISSUE TITLE
Gust Bellows requires Gust Bellows to obtain.

### ISSUE THREAD

**Issue by Denly1990** [lepelog/sslib#46]
Running Version 1.0.2, seed 773642. The Gust Bellows in my file are locked in a Goddess Chest, and the cube to unlock it is located on the Great Tree (specifically the one across from the Viewing Platform). However, to climb the tree, the Gust Bellows are to my knowledge required to pass the swinging platforms inside the Great Tree. Trying to attack the cube from other angles with a Skyward Strike hasn't worked to the best of my abilities. The angle from the Clawshot Goddess Cube has a wall between Link and the Cube, and the platform's ledge blocks from using the Crow enemies below to angle a Skyward Strike upward towards the cube.

**Comment by azer67** [comment]
You can climb the Great Tree with the Clawshots. Go near the freestanding item near the rope, and clawshot up to the vines. I'm not sure which of the 3 cubes you're describing, but no matter the cube you can jump down to it from the top of the Great Tree.
