### ISSUE TITLE
Missing sandship

### ISSUE THREAD

**Issue by Maximus-Gaming** [lepelog/sslib#65]
My dowsing function is set to the trial gates so the ship didn't spawn. I checked around the spot it is supossed to be with the cannon, but no luck. I also couldn't enter the ship yet at the place you are normally able to.

**Comment by olohr** [comment]
As long as you have gotten the ancient Sea Chart, you can dowse for the Sandship, even if the dowsing icon isn't updated correctly (top option on the dowsing wheel)

**Comment by Maximus-Gaming** [comment]
I see, thanks for the reply. I had visited the skipper after getting the sea chart bit dowsing again hadn’t come to mind. This worked as intended as I was just able to find the ship via dowsing.
