### ISSUE TITLE
Unbeatable Seed

### ISSUE THREAD

**Issue by shiren45** [lepelog/sslib#73]
[SS Random -89 - Spoiler Log.txt](https://github.com/lepelog/sslib/files/5923630/SS.Random.-89.-.Spoiler.Log.txt)

There is no way to access the Horned Collossus Beetle in Skipper's Retreat, which is locking the Emerald Tablet and Skyview is a required dungeon.

**Comment by lepelog** [comment]
With the whip, you can actually grab the bomb flower on top of the cactus next to the rock you need to blow up to progress in skippers retreat.

**Comment by shiren45** [comment]
The funny part is I tried this before I posted the issue. And now I try it again and it totally works. Props on putting that in the logic, since I don't think a casual player would know to do that. I forget that SS has those weird random quirks that the game doesn't exactly tell you. Although now I feel kinda dumb for asking, my bad. Thanks for the help.
