### ISSUE TITLE
Problem when writing patched game

### ISSUE THREAD

**Issue by n4tou69** [lepelog/sslib#74]
When I click on "randomize" in ssrando.exe, a window appears with "patch ....." then "writing patched game" but it gets stuck at 99 % and never finishes the process.
![random](https://user-images.githubusercontent.com/78729364/107205726-788c4380-69fe-11eb-8a0c-3cd93f81deb5.PNG)

I waited a few hours and I still don't don't know what to do to fix it, please help!

**Comment by n4tou69** [comment]
I also get this error : "Running from source without git is not supported!"

**Comment by lepelog** [comment]
That is probably the issue then. You either have to use git, in order to run the randomizer directly from source, or you have to use a compiled release: https://github.com/lepelog/sslib/releases/tag/1.0.4
