### ISSUE TITLE
[Suggestion] Include Seed in permalink.

### ISSUE THREAD

**Issue by Crain-32** [lepelog/sslib#76]
Bundling the user's inputted seed (Ignoring the `seed_key`) into the permalink allows for easier distribution of seeds, something which is very help in a racing standpoint, and a community standpoint. It would be very nice.

**Comment by lepelog** [comment]
The reason for not including the seed in the permalink was to make it easier to use the same settings, but with different seeds. Or is there a way to make a settings string that is for a random seed? I guess something like `settings!seed` would work, allowing to share both in one string or only the settings, in which case it would be random
