### ISSUE TITLE
Pouch won't open

### ISSUE THREAD

**Issue by link7596** [lepelog/sslib#96]
The game is acting as if I have the cursed medal equipped. I'm 100% positive I don't have it, but I have acquired the item from the cursed medal chest, which was bombs, so that might have something to do with it. Medals and items like extra bomb bag work normally, I just can't open the pouch and use bottles or shields. I'm at a fine level of skill so I can beat the game without pouch access, but all of the dungeons are required and I can't get into fire sanctuary or ancient cistern. I won't be able to beat the seed without a bottle, is there a fix to this?

**Comment by lepelog** [comment]
Did you start with pouch? It might be randomized, then you have to find it first before you can use it.
You can also talk to peatrice in the bazaar to make sure you don't have cursed medal

**Comment by link7596** [comment]
I didn't start with pouch, but I have obtained it, and I can put stuff in it with item check. I don't have the cursed medal in my pouch, I actually haven't gotten it at all yet. The pouch works like normal with medals, like the life medal still gives me an extra heart container, it just doesn't open by holding -  like it would normally. An additional note is that when I go to the gear menu and try to look at my pouch, it doesn't do anything when I push -, and that would normally work even with cursed medal, so the game is sort of acting like I don't have the pouch, but I am sure I have it because I remember getting it and item check works. Thanks for responding and helping me with the issue!

**Comment by lepelog** [comment]
That sounds like the storyflag for the pouch is not set, which is very weird. But that explains why you can't open it and why you can't see it in the inventory menu. Can you post your spoiler log here and tell me which pouch you got? That way I can hopefully reproduce the bug and work on fixing it

**Comment by lepelog** [comment]
Also, did anything weird happen when you got the pouch? I assume you weren't able to open it right after obtaining?

**Comment by link7596** [comment]
[SS Random 10322 - Spoiler Log.txt](https://github.com/lepelog/sslib/files/6619316/SS.Random.10322.-.Spoiler.Log.txt)
it is goddess chest next to bamboo island. The only thing that i thought was strange when I first got it was that it gave an extra pouch slot as well as the pouch in one item, so I basically started with 5 and never had 4 slots. That might be intended but i'm not sure. I was never able to open it even right after obtaining.

**Comment by link7596** [comment]
That's it! You're totally right, I am using a hero mode file. It's unfortunate I have to start over, but I'm looking forward to being able to play through the whole thing now, thank you for your help!
